name: 'Stylus Trace Diff'
description: 'Profile Arbitrum Stylus transactions and detect gas regressions'
inputs:
  tx_hash:
    description: 'Transaction hash to profile'
    required: true
  rpc_url:
    description: 'RPC endpoint URL'
    required: false
    default: 'http://localhost:8547'
  baseline:
    description: 'Path to baseline profile'
    required: false
  threshold_percent:
    description: 'Threshold percentage for regression gating'
    required: false
  ink:
    description: 'Use Stylus Ink units'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Install stylus-trace
      shell: bash
      run: |
        if ! command -v stylus-trace &> /dev/null; then
          cargo install --git https://github.com/CreativesOnchain/Stylus-Trace.git stylus-trace
        fi

    - name: Capture Profile
      shell: bash
      run: |
        # stylus-trace auto-resolves relative paths into artifacts/capture/
        # so we pass just the filename, not the full path
        FLAGS="--tx ${{ inputs.tx_hash }} --rpc ${{ inputs.rpc_url }} --summary --flamegraph --output profile.json"
        if [ "${{ inputs.ink }}" == "true" ]; then FLAGS="$FLAGS --ink"; fi
        if [ -n "${{ inputs.baseline }}" ] && [ -f "${{ inputs.baseline }}" ]; then FLAGS="$FLAGS --baseline ${{ inputs.baseline }}"; fi
        if [ -n "${{ inputs.threshold_percent }}" ]; then FLAGS="$FLAGS --threshold-percent ${{ inputs.threshold_percent }}"; fi

        mkdir -p artifacts/capture
        echo "Running: stylus-trace capture $FLAGS"
        stylus-trace capture $FLAGS
